services:
  meting-calendar:
    build:
      context: .
    container_name: meting-calendar-service
    ports:
      - "8001:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: meting-calendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: meetingCalendar
    ports:
      - "27111:27017"
    volumes:
      - meting-calendar-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: meting-calendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetingCalendar
    ports:
      - "5113:5432"
    volumes:
      - meting-calendar-postgresql:/data/db/postgresql

volumes:
  meting-calendar-mongodb:
    driver: local
  meting-calendar-postgresql:
    driver: local
